# Generated by Django 5.2.1 on 2025-06-04 03:19

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=50, unique=True, validators=[utils.validators.validate_email], verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=50, validators=[utils.validators.validate_full_name], verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, validators=[utils.validators.validate_full_name], verbose_name='Apellidos')),
                ('dni', models.CharField(blank=True, error_messages={'unique': 'Ya existe un usuario con esta cédula.'}, max_length=10, null=True, unique=True, validators=[utils.validators.validate_dni], verbose_name='Cédula')),
                ('address', models.CharField(blank=True, max_length=255, null=True, validators=[utils.validators.validate_address_and_city], verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=255, null=True, validators=[utils.validators.validate_address_and_city], verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, error_messages={'unique': 'Ya existe un usuario con este número de teléfono.'}, max_length=20, null=True, unique=True, validators=[utils.validators.validate_phone], verbose_name='Teléfono')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[utils.validators.validate_profile_picture], verbose_name='Foto de perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
