# Generated by Django 5.2.1 on 2025-05-27 06:41

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=50, unique=True, validators=[utils.validators.validate_email], verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=50, validators=[utils.validators.validate_full_name], verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, validators=[utils.validators.validate_full_name], verbose_name='Apellidos')),
                ('dni', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[utils.validators.validate_dni], verbose_name='Cédula')),
                ('address', models.CharField(blank=True, max_length=255, null=True, validators=[utils.validators.validate_address_and_city], verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=255, null=True, validators=[utils.validators.validate_address_and_city], verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[utils.validators.validate_phone], verbose_name='Teléfono')),
                ('profile_picture', models.ImageField(blank=True, default='static/img/avatar.avif', null=True, upload_to='profile_pictures/', validators=[utils.validators.validate_profile_picture], verbose_name='Foto de perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='Permisos de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
