# Generated by Django 5.2.1 on 2025-06-15 19:54

import utils.s3_storage
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.s3_storage.S3ProfilePictureStorage(), upload_to='', validators=[utils.validators.validate_profile_picture], verbose_name='Foto de perfil'),
        ),
    ]
