# Generated by Django 5.2.1 on 2025-05-27 07:03

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/img/avatar.jpg', null=True, upload_to='profile_pictures/', validators=[utils.validators.validate_profile_picture], verbose_name='Foto de perfil'),
        ),
    ]
