# Generated by Django 5.2.1 on 2025-05-28 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre del paciente', max_length=100)),
                ('last_name', models.CharField(help_text='Apellido del paciente', max_length=100)),
                ('dni', models.CharField(help_text='Documento de identidad del paciente', max_length=20)),
                ('phone', models.CharField(help_text='Teléfono de contacto', max_length=20)),
                ('email', models.EmailField(help_text='Correo electrónico', max_length=254)),
                ('image', models.ImageField(upload_to='skin_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('gradcam_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_report', models.TextField(blank=True, null=True)),
                ('ai_treatment', models.TextField(blank=True, null=True)),
                ('age_approx', models.PositiveIntegerField(help_text='Edad aproximada del paciente (0-120).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('sex', models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino'), ('unknown', 'Desconocido/No especificado')], default='unknown', help_text='Sexo del paciente.', max_length=10)),
                ('anatom_site_general', models.CharField(choices=[('abdomen', 'Abdomen'), ('acral', 'Acral (Palmas, Plantas, Dedos)'), ('anterior torso', 'Torso Anterior'), ('back', 'Espalda'), ('chest', 'Pecho'), ('ear', 'Oreja'), ('face', 'Cara'), ('foot', 'Pie'), ('genital', 'Genital'), ('hand', 'Mano'), ('head/neck', 'Cabeza/Cuello'), ('lateral torso', 'Torso Lateral'), ('lower extremity', 'Extremidad Inferior'), ('neck', 'Cuello'), ('oral/genital', 'Oral/Genital'), ('palms/soles', 'Palmas/Plantas'), ('posterior torso', 'Torso Posterior'), ('scalp', 'Cuero Cabelludo'), ('trunk', 'Tronco (General)'), ('unknown', 'Desconocida/Otra'), ('upper extremity', 'Extremidad Superior')], default='unknown', help_text='Localización anatómica general de la lesión.', max_length=50)),
            ],
        ),
    ]
