# Generated by Django 5.2.1 on 2025-06-04 03:19

import django.core.validators
import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[utils.validators.validate_full_name])),
                ('last_name', models.CharField(max_length=50, validators=[utils.validators.validate_full_name])),
                ('dni', models.CharField(error_messages={'unique': 'Ya existe un usuario con esta cédula.'}, max_length=10, unique=True, validators=[utils.validators.validate_dni], verbose_name='Cédula')),
                ('phone', models.CharField(error_messages={'unique': 'Ya existe un usuario con este número de teléfono.'}, max_length=20, unique=True, validators=[utils.validators.validate_phone], verbose_name='Teléfono')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=50, unique=True, validators=[utils.validators.validate_email], verbose_name='Correo electrónico')),
                ('age_approx', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'La edad no puede ser negativa'), django.core.validators.MaxValueValidator(110, 'La edad máxima permitida es 110 años')])),
                ('sex', models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino')], max_length=10)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SkinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skin_images/', validators=[utils.validators.validate_profile_picture])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('processed', models.BooleanField(blank=True, default=False, null=True)),
                ('condition', models.CharField(blank=True, help_text='Condición dermatológica detectada por la IA', max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'La confianza no puede ser negativa'), django.core.validators.MaxValueValidator(1.0, 'La confianza no puede ser mayor a 1')])),
                ('gradcam_path', models.CharField(blank=True, help_text='Ruta a la imagen de visualización GradCAM', max_length=255, null=True)),
                ('ai_report', models.TextField(blank=True, null=True)),
                ('ai_treatment', models.TextField(blank=True, null=True)),
                ('anatom_site_general', models.CharField(choices=[('abdomen', 'Abdomen'), ('acral', 'Acral (Palmas, Plantas, Dedos)'), ('anterior_torso', 'Torso Anterior'), ('back', 'Espalda'), ('chest', 'Pecho'), ('ear', 'Oreja'), ('face', 'Cara'), ('foot', 'Pie'), ('genital', 'Genital'), ('hand', 'Mano'), ('head_neck', 'Cabeza/Cuello'), ('lateral_torso', 'Torso Lateral'), ('lower_extremity', 'Extremidad Inferior'), ('neck', 'Cuello'), ('oral_genital', 'Oral/Genital'), ('palms_soles', 'Palmas/Plantas'), ('posterior_torso', 'Torso Posterior'), ('scalp', 'Cuero Cabelludo'), ('trunk', 'Tronco (General)'), ('upper_extremity', 'Extremidad Superior'), ('unknown', 'Desconocida/Otra')], default='Desconocida', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='Dermatologia_IA.patient')),
            ],
            options={
                'verbose_name': 'Imagen Dermatológica',
                'verbose_name_plural': 'Imágenes Dermatológicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
